name: selection_controls
description: A new Flutter package project.
version: 0.4.0
homepage:

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: